const hotelPersonas=[
{id:0,email:'lena@harbor-oak.example',focus:{en:'Owns opening decisions, cash commitments and the weekly business review. Receives summaries instead of every team transcript.',de:'Verantwortet Eröffnungsentscheidungen, Ausgaben und den Wochenbericht. Erhält Zusammenfassungen statt aller Team-Transkripte.'},rhythm:{en:'Friday · 16:00 business review',de:'Freitag · 16:00 Business Review'}},
{id:1,email:'david@harbor-oak.example',focus:{en:'Builds the corporate pipeline and turns launch interest into qualified hotel enquiries. Coordinates offers with Revenue and Marketing.',de:'Baut Firmenkundengeschäft auf und macht aus Launch-Interesse konkrete Hotelanfragen. Stimmt Angebote mit Revenue und Marketing ab.'},rhythm:{en:'Monday · 09:00 commercial stand-up',de:'Montag · 09:00 Commercial Stand-up'}},
{id:2,email:'sofia@harbor-oak.example',focus:{en:'Owns rates, channel accuracy and the opening forecast. Checks that campaigns protect price and that reports use net room revenue.',de:'Verantwortet Raten, Kanäle und die Eröffnungsprognose. Prüft Preisdisziplin und den Netto-Zimmerumsatz in Berichten.'},rhythm:{en:'Wednesday · 12:30 channel check',de:'Mittwoch · 12:30 Kanalprüfung'}},
{id:3,email:'jonas@harbor-oak.example',focus:{en:'Coordinates room readiness, suppliers and the guest journey. Tests room equipment and the summer bedding samples with the team.',de:'Koordiniert Zimmerbereitschaft, Lieferanten und Gästereise. Testet Zimmerausstattung und Sommerdeckenmuster mit dem Team.'},rhythm:{en:'Monday · 08:30 operations check',de:'Montag · 08:30 Operations-Check'}},
{id:4,email:'mia@harbor-oak.example',focus:{en:'Owns the content calendar, creator preview and direct-booking tracking. Turns operational facts into accurate guest communication.',de:'Verantwortet Redaktionsplan, Creator Preview und Direktbuchungs-Tracking. Macht aus Betriebsinformationen verlässliche Gästekommunikation.'},rhythm:{en:'Friday · 09:00 campaign handoff',de:'Freitag · 09:00 Kampagnenübergabe'}},
{id:5,email:'amira@harbor-oak.example',focus:{en:'Recruits the service team and prepares service training. Works with Operations on shift coverage and the soft-opening rehearsal.',de:'Rekrutiert das Service-Team und bereitet Trainings vor. Stimmt Schichtbesetzung und Soft-Opening-Proben mit Operations ab.'},rhythm:{en:'Wednesday · 11:00 service academy',de:'Mittwoch · 11:00 Service Academy'}}
];
const hotelProjects=[
{id:'readiness',name:{en:'Rooms ready for opening',de:'Zimmer bereit zur Eröffnung'},description:{en:'Technical sign-off, linen procurement and the final guest-journey rehearsal.',de:'Technische Abnahme, Wäschebeschaffung und die letzte Probe der Gästereise.'},lead:3,members:[3,5],taskIds:[4,8,9,12,23],meetingIds:[3],due:'2026-09-24',priority:1,color:'#7b9673',outcome:{en:'164 rooms signed off before the opening gate.',de:'164 abgenommene Zimmer vor der Eröffnungsfreigabe.'}},
{id:'commercial',name:{en:'Corporate sales & autumn revenue',de:'Firmenkunden & Herbst-Revenue'},description:{en:'Corporate agreements, trade-fair pricing and distribution readiness for October.',de:'Firmenvereinbarungen, Messeraten und vertriebsbereite Kanäle für Oktober.'},lead:2,members:[0,1,2],taskIds:[2,3,6,7,18,19,21],meetingIds:[2,6],due:'2026-09-18',priority:2,color:'#7f91b4',outcome:{en:'A reliable opening forecast and signed corporate business.',de:'Verlässliche Eröffnungsprognose und abgeschlossenes Firmenkundengeschäft.'}},
{id:'direct',name:{en:'Direct booking & brand launch',de:'Direktbuchung & Markenlaunch'},description:{en:'Content, campaign attribution and the creator preview. Three detailed team meetings follow the same commitments through one week.',de:'Content, Kampagnenmessung und Creator Preview. Drei ausführliche Team-Meetings verfolgen dieselben Zusagen über eine Woche.'},lead:4,members:[1,2,4],taskIds:[11,13,14,20,24],meetingIds:[4,10,11,12],due:'2026-09-25',priority:3,color:'#b68a79',outcome:{en:'A measurable launch that brings guests into the direct-booking flow.',de:'Ein messbarer Launch, der Gäste zur Direktbuchung führt.'}},
{id:'academy',name:{en:'People & service academy',de:'People & Service Academy'},description:{en:'Hiring, shift buddies and service standards for a consistent first guest experience.',de:'Recruiting, Schicht-Buddies und Service-Standards für ein einheitliches erstes Gästeerlebnis.'},lead:5,members:[3,5],taskIds:[5,15,16,17],meetingIds:[5,8],due:'2026-09-22',priority:4,color:'#b09a6a',outcome:{en:'A fully staffed, trained team for the soft opening.',de:'Ein vollständig besetztes, geschultes Team zum Soft Opening.'}},
{id:'comfort',name:{en:'Summer sleep comfort 2027',de:'Sommer-Schlafkomfort 2027'},description:{en:'Supplier samples, wash tests and verified material information for breathable summer quilts.',de:'Lieferantenmuster, Waschtests und geprüfte Materialangaben für atmungsaktive Sommerdecken.'},lead:3,members:[3,4],taskIds:[25,26],meetingIds:[9],due:'2026-09-30',priority:5,color:'#759ca6',outcome:{en:'An evidence-based shortlist before any bedding order is placed.',de:'Eine geprüfte Vorauswahl, bevor Bettwaren bestellt werden.'}},
{id:'leadership',name:{en:'Opening decisions & weekly review',de:'Eröffnungsentscheidungen & Wochenreview'},description:{en:'Lena’s personal decision list, supplier approvals and Friday business review.',de:'Lenas persönliche Entscheidungsliste, Lieferantenfreigaben und Business Review am Freitag.'},lead:0,members:[0],taskIds:[1,10,22],meetingIds:[1,7],due:'2026-10-01',priority:6,color:'#737e83',outcome:{en:'Clear decisions without reading every team conversation.',de:'Klare Entscheidungen, ohne jedes Teamgespräch lesen zu müssen.'}}
];
function projectTasks(project,records=tasks){return records.filter(t=>t.projectId===project.id||project.taskIds.includes(t.id))}
function projectPeople(project,records=tasks){return [...new Set([...project.members,...projectTasks(project,records).map(t=>t.owner)])]}
function taskStats(records){const count=records.length,completed=records.filter(t=>t.status==='Erledigt').length,progressSum=records.reduce((sum,t)=>sum+t.progress,0);return {count,completed,open:count-completed,blocked:records.filter(t=>t.status==='Blockiert').length,progress:count?progressSum/count:0,progressSum}}
function projectStats(project,records=tasks){return taskStats(projectTasks(project,records))}
// Opening-month booked room nights, as of Friday 11 September. Net room revenue excludes taxes and extras.
const hotelForecast={asOf:'2026-09-11',stayFrom:'2026-10-05',stayTo:'2026-10-11',rooms:164,days:[
{date:'2026-10-05',sold:96,adr:180,direct:38},
{date:'2026-10-06',sold:102,adr:185,direct:41},
{date:'2026-10-07',sold:108,adr:190,direct:44},
{date:'2026-10-08',sold:118,adr:200,direct:48},
{date:'2026-10-09',sold:142,adr:220,direct:62},
{date:'2026-10-10',sold:146,adr:225,direct:66},
{date:'2026-10-11',sold:92,adr:170,direct:43}],
previous:{sold:756,revenue:146664,direct:304},targets:{occupancy:75,adr:200,directShare:45},grossNights:840,cancelledNights:36,readyRooms:148,
source:{en:'Fictional reservations export · same seven stay dates for both snapshots',de:'Fiktiver Reservierungsexport · identische sieben Aufenthaltsdaten für beide Stände'}};
function calculateHotelKPIs(forecast=hotelForecast){const available=forecast.rooms*forecast.days.length,sold=forecast.days.reduce((n,d)=>n+d.sold,0),revenue=forecast.days.reduce((n,d)=>n+d.sold*d.adr,0),direct=forecast.days.reduce((n,d)=>n+d.direct,0);return {available,sold,revenue,direct,occupancy:available?sold/available*100:0,adr:sold?revenue/sold:0,revpar:available?revenue/available:0,directShare:sold?direct/sold*100:0,cancellationRate:forecast.grossNights?forecast.cancelledNights/forecast.grossNights*100:0,readiness:forecast.rooms?forecast.readyRooms/forecast.rooms*100:0,pickup:sold-forecast.previous.sold,occupancyDelta:available?(sold-forecast.previous.sold)/available*100:0,revparDelta:available?(revenue-forecast.previous.revenue)/available:0}}
function lastFridayAtSixteen(now=new Date()){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hourCycle:'h23'}).formatToParts(now).map(p=>[p.type,p.value]));const date=new Date(`${parts.year}-${parts.month}-${parts.day}T12:00:00Z`);let back=(date.getUTCDay()-5+7)%7;if(back===0&&Number(parts.hour)<16)back=7;date.setUTCDate(date.getUTCDate()-back);return date.toISOString().slice(0,10)}
function buildReportSnapshot(friday,records=tasks){return {id:friday,scheduledFor:friday+' 16:00 Europe/Berlin',createdAt:new Date().toISOString(),forecast:JSON.parse(JSON.stringify(hotelForecast)),kpis:calculateHotelKPIs(),projects:hotelProjects.map(p=>({id:p.id,name:p.name,lead:p.lead,people:projectPeople(p,records),...projectStats(p,records)})),totals:taskStats(records),inboxStatus:'available',emailStatus:'not_connected',demo:true}}
